//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class CatClientes : XPObject
  {
    private icoSPVenta.Module.BusinessObjects.CatTipoDeVenta _oidTipoDeVenta;
    private System.String _nombre;
    private System.String _materno;
    private System.String _paterno;
    public CatClientes(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String Paterno
    {
      get
      {
        return _paterno;
      }
      set
      {
        SetPropertyValue("Paterno", ref _paterno, value);
      }
    }
    public System.String Materno
    {
      get
      {
        return _materno;
      }
      set
      {
        SetPropertyValue("Materno", ref _materno, value);
      }
    }
    public System.String Nombre
    {
      get
      {
        return _nombre;
      }
      set
      {
        SetPropertyValue("Nombre", ref _nombre, value);
      }
    }
    public icoSPVenta.Module.BusinessObjects.CatTipoDeVenta OidTipoDeVenta
    {
      get
      {
        return _oidTipoDeVenta;
      }
      set
      {
        SetPropertyValue("OidTipoDeVenta", ref _oidTipoDeVenta, value);
      }
    }
  }
}
