//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class CatCajas : XPObject
  {
    private icoSPVenta.Module.BusinessObjects.Usuario _oidUsuario;
    private System.Int32 _numeroCaja;
    private System.Boolean _ticket;
    private System.Boolean _disponible;
    private System.String _descripcionCaja;
    public CatCajas(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.Int32 NumeroCaja
    {
      get
      {
        return _numeroCaja;
      }
      set
      {
        SetPropertyValue("NumeroCaja", ref _numeroCaja, value);
      }
    }
    public System.String DescripcionCaja
    {
      get
      {
        return _descripcionCaja;
      }
      set
      {
        SetPropertyValue("DescripcionCaja", ref _descripcionCaja, value);
      }
    }
    public System.Boolean Disponible
    {
      get
      {
        return _disponible;
      }
      set
      {
        SetPropertyValue("Disponible", ref _disponible, value);
      }
    }
    public icoSPVenta.Module.BusinessObjects.Usuario OidUsuario
    {
      get
      {
        return _oidUsuario;
      }
      set
      {
        SetPropertyValue("OidUsuario", ref _oidUsuario, value);
      }
    }
    public System.Boolean Ticket
    {
      get
      {
        return _ticket;
      }
      set
      {
        SetPropertyValue("Ticket", ref _ticket, value);
      }
    }
  }
}
