//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class CatUnidadMedida : XPObject
  {
    private System.String _descripcionUnidadMedida;
    public CatUnidadMedida(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String DescripcionUnidadMedida
    {
      get
      {
        return _descripcionUnidadMedida;
      }
      set
      {
        SetPropertyValue("DescripcionUnidadMedida", ref _descripcionUnidadMedida, value);
      }
    }
  }
}
