//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class DatosEmpresa : XPObject
  {
    private System.Int32 _codigoPostal;
    private System.Int32 _telefono;
    private System.String _rFC;
    private System.String _colonia;
    private System.String _estado;
    private System.String _ciudad;
    private System.String _direccion;
    private System.String _nombreEmpresa;
    public DatosEmpresa(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String NombreEmpresa
    {
      get
      {
        return _nombreEmpresa;
      }
      set
      {
        SetPropertyValue("NombreEmpresa", ref _nombreEmpresa, value);
      }
    }
    public System.String Direccion
    {
      get
      {
        return _direccion;
      }
      set
      {
        SetPropertyValue("Direccion", ref _direccion, value);
      }
    }
    public System.Int32 Telefono
    {
      get
      {
        return _telefono;
      }
      set
      {
        SetPropertyValue("Telefono", ref _telefono, value);
      }
    }
    public System.String Ciudad
    {
      get
      {
        return _ciudad;
      }
      set
      {
        SetPropertyValue("Ciudad", ref _ciudad, value);
      }
    }
    public System.String Estado
    {
      get
      {
        return _estado;
      }
      set
      {
        SetPropertyValue("Estado", ref _estado, value);
      }
    }
    public System.Int32 CodigoPostal
    {
      get
      {
        return _codigoPostal;
      }
      set
      {
        SetPropertyValue("CodigoPostal", ref _codigoPostal, value);
      }
    }
    public System.String Colonia
    {
      get
      {
        return _colonia;
      }
      set
      {
        SetPropertyValue("Colonia", ref _colonia, value);
      }
    }
    public System.String RFC
    {
      get
      {
        return _rFC;
      }
      set
      {
        SetPropertyValue("RFC", ref _rFC, value);
      }
    }
  }
}
