//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class DetalleVentas : XPObject
  {
    private icoSPVenta.Module.BusinessObjects.Ventas _oidVenta;
    private System.Decimal _iVA;
    private icoSPVenta.Module.BusinessObjects.CatProductos _oidProducto;
    private System.Decimal _precioUnitario;
    private System.Int32 _cantidad;
    public DetalleVentas(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public icoSPVenta.Module.BusinessObjects.Ventas OidVenta
    {
      get
      {
        return _oidVenta;
      }
      set
      {
        SetPropertyValue("OidVenta", ref _oidVenta, value);
      }
    }
    public icoSPVenta.Module.BusinessObjects.CatProductos OidProducto
    {
      get
      {
        return _oidProducto;
      }
      set
      {
        SetPropertyValue("OidProducto", ref _oidProducto, value);
      }
    }
    public System.Int32 Cantidad
    {
      get
      {
        return _cantidad;
      }
      set
      {
        SetPropertyValue("Cantidad", ref _cantidad, value);
      }
    }
    public System.Decimal PrecioUnitario
    {
      get
      {
        return _precioUnitario;
      }
      set
      {
        SetPropertyValue("PrecioUnitario", ref _precioUnitario, value);
      }
    }
    public System.Decimal IVA
    {
      get
      {
        return _iVA;
      }
      set
      {
        SetPropertyValue("IVA", ref _iVA, value);
      }
    }

    [DevExpress.Xpo.AssociationAttribute("Ventas-DetalleVentas")]
    public icoSPVenta.Module.BusinessObjects.Ventas Venta
    {
        get
        {
            return _oidVenta;
        }
        set
        {
            SetPropertyValue("Ventas", ref _oidVenta, value);
        }
    }
  }
}
