//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class Promocion : XPObject
  {
    private System.DateTime _fechaInicio;
    private System.DateTime _fechaFinal;
    private System.Decimal _valorFinal;
    private System.Double _descuento;
    private System.Decimal _valorNormal;
    private icoSPVenta.Module.BusinessObjects.CatProductos _oidProducto;
    private System.String _nombrePromocion;
    public Promocion(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public icoSPVenta.Module.BusinessObjects.CatProductos OidProducto
    {
      get
      {
        return _oidProducto;
      }
      set
      {
        SetPropertyValue("OidProducto", ref _oidProducto, value);
      }
    }
    public System.String NombrePromocion
    {
      get
      {
        return _nombrePromocion;
      }
      set
      {
        SetPropertyValue("NombrePromocion", ref _nombrePromocion, value);
      }
    }
    public System.Decimal ValorNormal
    {
      get
      {
        return _valorNormal;
      }
      set
      {
        SetPropertyValue("ValorNormal", ref _valorNormal, value);
      }
    }
    public System.Double Descuento
    {
      get
      {
        return _descuento;
      }
      set
      {
        SetPropertyValue("Descuento", ref _descuento, value);
      }
    }
    public System.Decimal ValorFinal
    {
      get
      {
        return _valorFinal;
      }
      set
      {
        SetPropertyValue("ValorFinal", ref _valorFinal, value);
      }
    }
    public System.DateTime FechaInicio
    {
      get
      {
        return _fechaInicio;
      }
      set
      {
        SetPropertyValue("FechaInicio", ref _fechaInicio, value);
      }
    }
    public System.DateTime FechaFinal
    {
      get
      {
        return _fechaFinal;
      }
      set
      {
        SetPropertyValue("FechaFinal", ref _fechaFinal, value);
      }
    }
  }
}
