//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class TempVentas : XPObject
  {
    private System.Decimal _iVA;
    private System.Decimal _precioUnitario;
    private System.Int32 _cantidad;
    private System.Int32 _oidProducto;
    private System.String _oidUsuario;
    public TempVentas(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.Int32 OidProducto
    {
      get
      {
        return _oidProducto;
      }
      set
      {
        SetPropertyValue("OidProducto", ref _oidProducto, value);
      }
    }
    public System.String OidUsuario
    {
      get
      {
        return _oidUsuario;
      }
      set
      {
        SetPropertyValue("OidUsuario", ref _oidUsuario, value);
      }
    }
    public System.Int32 Cantidad
    {
      get
      {
        return _cantidad;
      }
      set
      {
        SetPropertyValue("Cantidad", ref _cantidad, value);
      }
    }
    public System.Decimal PrecioUnitario
    {
      get
      {
        return _precioUnitario;
      }
      set
      {
        SetPropertyValue("PrecioUnitario", ref _precioUnitario, value);
      }
    }
    public System.Decimal IVA
    {
      get
      {
        return _iVA;
      }
      set
      {
        SetPropertyValue("IVA", ref _iVA, value);
      }
    }
  }
}
