//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class Usuario : XPObject
  {
    private System.Boolean _consultas;
    private System.Boolean _deshacerVenta;
    private System.Boolean _catalogos;
    private System.Boolean _reportes;
    private System.Boolean _administrar;
    private System.Boolean _ventas;
    private System.String _nombre;
    private System.String _materno;
    private System.String _paterno;
    private System.String _contrasenaUsuario;
    private System.String _nombreUsuario;
    public Usuario(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String NombreUsuario
    {
      get
      {
        return _nombreUsuario;
      }
      set
      {
        SetPropertyValue("NombreUsuario", ref _nombreUsuario, value);
      }
    }
    public System.String ContrasenaUsuario
    {
      get
      {
        return _contrasenaUsuario;
      }
      set
      {
        SetPropertyValue("ContrasenaUsuario", ref _contrasenaUsuario, value);
      }
    }
    public System.String Paterno
    {
      get
      {
        return _paterno;
      }
      set
      {
        SetPropertyValue("Paterno", ref _paterno, value);
      }
    }
    public System.String Materno
    {
      get
      {
        return _materno;
      }
      set
      {
        SetPropertyValue("Materno", ref _materno, value);
      }
    }
    public System.String Nombre
    {
      get
      {
        return _nombre;
      }
      set
      {
        SetPropertyValue("Nombre", ref _nombre, value);
      }
    }
    public System.Boolean Ventas
    {
      get
      {
        return _ventas;
      }
      set
      {
        SetPropertyValue("Ventas", ref _ventas, value);
      }
    }
    public System.Boolean Administrar
    {
      get
      {
        return _administrar;
      }
      set
      {
        SetPropertyValue("Administrar", ref _administrar, value);
      }
    }
    public System.Boolean Reportes
    {
      get
      {
        return _reportes;
      }
      set
      {
        SetPropertyValue("Reportes", ref _reportes, value);
      }
    }
    public System.Boolean Catalogos
    {
      get
      {
        return _catalogos;
      }
      set
      {
        SetPropertyValue("Catalogos", ref _catalogos, value);
      }
    }
    public System.Boolean Consultas
    {
      get
      {
        return _consultas;
      }
      set
      {
        SetPropertyValue("Consultas", ref _consultas, value);
      }
    }
    public System.Boolean DeshacerVenta
    {
      get
      {
        return _deshacerVenta;
      }
      set
      {
        SetPropertyValue("DeshacerVenta", ref _deshacerVenta, value);
      }
    }
  }
}
