//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class Ventas : XPObject
  {
    private icoSPVenta.Module.BusinessObjects.CatTipoPago _oidTipoDePago;
    private icoSPVenta.Module.BusinessObjects.Usuario _oidUsuario;
    private System.Decimal _total;
    private icoSPVenta.Module.BusinessObjects.CatClientes _cliente;
    private icoSPVenta.Module.BusinessObjects.CatCajas _caja;
    private System.DateTime _fecha;
    private System.Int32 _folio;
    public Ventas(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.Int32 Folio
    {
      get
      {
        return _folio;
      }
      set
      {
        SetPropertyValue("Folio", ref _folio, value);
      }
    }
    public System.DateTime Fecha
    {
      get
      {
        return _fecha;
      }
      set
      {
        SetPropertyValue("Fecha", ref _fecha, value);
      }
    }
    public icoSPVenta.Module.BusinessObjects.Usuario OidUsuario
    {
      get
      {
        return _oidUsuario;
      }
      set
      {
        SetPropertyValue("OidUsuario", ref _oidUsuario, value);
      }
    }
    public System.Decimal Total
    {
      get
      {
        return _total;
      }
      set
      {
        SetPropertyValue("Total", ref _total, value);
      }
    }
    public icoSPVenta.Module.BusinessObjects.CatCajas Caja
    {
      get
      {
        return _caja;
      }
      set
      {
        SetPropertyValue("Caja", ref _caja, value);
      }
    }
    public icoSPVenta.Module.BusinessObjects.CatClientes Cliente
    {
      get
      {
        return _cliente;
      }
      set
      {
        SetPropertyValue("Cliente", ref _cliente, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Ventas-DetalleVentas"),
    DevExpress.Xpo.Aggregated]
    public XPCollection<icoSPVenta.Module.BusinessObjects.DetalleVentas> DetalleVenta
    {
      get
      {
        return GetCollection<icoSPVenta.Module.BusinessObjects.DetalleVentas>("DetalleVenta");
      }
    }
    public icoSPVenta.Module.BusinessObjects.CatTipoPago OidTipoDePago
    {
      get
      {
        return _oidTipoDePago;
      }
      set
      {
        SetPropertyValue("OidTipoDePago", ref _oidTipoDePago, value);
      }
    }
  }
}
