//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace icoSPVenta.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class Ventas : XPObject
  {
    private System.Decimal _total;
    private System.String _nombreUsuario;
    private icoSPVenta.Module.BusinessObjects.CatClientes _cliente;
    private icoSPVenta.Module.BusinessObjects.CatCajas _caja;
    private System.DateTime _fecha;
    private System.Int32 _folio;
    public Ventas(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.Int32 Folio
    {
      get
      {
        return _folio;
      }
      set
      {
        SetPropertyValue("Folio", ref _folio, value);
      }
    }
    public System.DateTime Fecha
    {
      get
      {
        return _fecha;
      }
      set
      {
        SetPropertyValue("Fecha", ref _fecha, value);
      }
    }
    public System.String NombreUsuario
    {
      get
      {
        return _nombreUsuario;
      }
      set
      {
        SetPropertyValue("NombreUsuario", ref _nombreUsuario, value);
      }
    }
    public System.Decimal Total
    {
      get
      {
        return _total;
      }
      set
      {
        SetPropertyValue("Total", ref _total, value);
      }
    }
    public icoSPVenta.Module.BusinessObjects.CatCajas Caja
    {
      get
      {
        return _caja;
      }
      set
      {
        SetPropertyValue("Caja", ref _caja, value);
      }
    }
    public icoSPVenta.Module.BusinessObjects.CatClientes Cliente
    {
      get
      {
        return _cliente;
      }
      set
      {
        SetPropertyValue("Cliente", ref _cliente, value);
      }
    }
  }
}
